name: Frontend Build & SonarQube Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-scan:
    name: Build Frontend & Scan with SonarQube
    runs-on: [self-hosted, frontend]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

